# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Projects\Proj_Z_Phenology\codes\mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 920)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 471, 421))
        self.groupBox.setObjectName("groupBox")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setGeometry(QtCore.QRect(20, 20, 432, 320))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 10, 471, 421))
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView_image2 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_image2.setGeometry(QtCore.QRect(20, 20, 432, 320))
        self.graphicsView_image2.setObjectName("graphicsView_image2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 440, 471, 421))
        self.groupBox_3.setObjectName("groupBox_3")
        self.graphicsView_image3 = QtWidgets.QGraphicsView(self.groupBox_3)
        self.graphicsView_image3.setGeometry(QtCore.QRect(20, 30, 432, 320))
        self.graphicsView_image3.setObjectName("graphicsView_image3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(520, 440, 471, 421))
        self.groupBox_4.setObjectName("groupBox_4")
        self.graphicsView_image4 = QtWidgets.QGraphicsView(self.groupBox_4)
        self.graphicsView_image4.setGeometry(QtCore.QRect(20, 30, 432, 320))
        self.graphicsView_image4.setObjectName("graphicsView_image4")
        self.graphicsView_gcc1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_gcc1.setGeometry(QtCore.QRect(1010, 20, 860, 200))
        self.graphicsView_gcc1.setObjectName("graphicsView_gcc1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1010, 240, 860, 200))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1010, 470, 860, 200))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1010, 700, 860, 200))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1900, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Phenocam01"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Phenocam02"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Phenocam03"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Phenocam04"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
