# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Projects\Proj_Z_Phenology\codes\mainform_Qlabel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 930)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 471, 421))
        self.groupBox.setObjectName("groupBox")
        self.label_image1 = QtWidgets.QLabel(self.groupBox)
        self.label_image1.setGeometry(QtCore.QRect(10, 20, 451, 391))
        self.label_image1.setObjectName("label_image1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 10, 471, 421))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_image2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_image2.setGeometry(QtCore.QRect(10, 20, 451, 391))
        self.label_image2.setObjectName("label_image2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 460, 471, 421))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_image3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_image3.setGeometry(QtCore.QRect(10, 20, 451, 391))
        self.label_image3.setObjectName("label_image3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(520, 460, 471, 421))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_image4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_image4.setGeometry(QtCore.QRect(10, 20, 451, 391))
        self.label_image4.setObjectName("label_image4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setGeometry(QtCore.QRect(1010, 10, 871, 871))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_gcc1 = QtWidgets.QLabel(self.groupBox_5)
        self.label_gcc1.setGeometry(QtCore.QRect(10, 20, 851, 200))
        self.label_gcc1.setObjectName("label_gcc1")
        self.label_gcc2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_gcc2.setGeometry(QtCore.QRect(10, 230, 851, 200))
        self.label_gcc2.setObjectName("label_gcc2")
        self.label_gcc3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_gcc3.setGeometry(QtCore.QRect(10, 440, 851, 200))
        self.label_gcc3.setObjectName("label_gcc3")
        self.label_gcc4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_gcc4.setGeometry(QtCore.QRect(10, 650, 851, 200))
        self.label_gcc4.setObjectName("label_gcc4")
        self.groupBox_5.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1900, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Phenocam01"))
        self.label_image1.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Phenocam02"))
        self.label_image2.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Phenocam03"))
        self.label_image3.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Phenocam04"))
        self.label_image4.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Phenocam04"))
        self.label_gcc1.setText(_translate("MainWindow", "TextLabel"))
        self.label_gcc2.setText(_translate("MainWindow", "TextLabel"))
        self.label_gcc3.setText(_translate("MainWindow", "TextLabel"))
        self.label_gcc4.setText(_translate("MainWindow", "TextLabel"))
